/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { BallotContract__factory } from "./BallotContract__factory";
export { VoterRegistry__factory } from "./VoterRegistry__factory";
