/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { BallotContract } from "./BallotContract";
export type { VoterRegistry } from "./VoterRegistry";
export * as factories from "./factories";
export { BallotContract__factory } from "./factories/BallotContract__factory";
export type { IVoter } from "./interfaces/IVoter";
export { IVoter__factory } from "./factories/interfaces/IVoter__factory";
export { VoterRegistry__factory } from "./factories/VoterRegistry__factory";
